language:
  - objective-c

osx_image: xcode7.3

env:
  - DEVICE=9.2

node_js:
  - "4.0"

install:
  - node --version
  - npm install
  - npm install -g gulp

script:
  - npm run test

after_success:
  - npm run coveralls
