language:
  - objective-c
osx_image: xcode7.3
env:
  - DEVICE=9.2
  - DEVICE=9.3
node_js:
  - "0.12"
install:
  - node --version
  - npm install
  - npm install -g gulp
script:
  - gulp once
  - _FORCE_LOGS=1 gulp e2e-test
after_success:
  - gulp coveralls